// GPL-2

// WARNING: This file has automatically been generated on Sun, 01 Nov 2020 21:26:34 EST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package btrfsutil

/*
#cgo LDFLAGS: -lbtrfsutil
#include <btrfsutil.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// BtrfsUtilVersionMajor as defined in include/btrfsutil.h:28
	BtrfsUtilVersionMajor = 1
	// BtrfsUtilVersionMinor as defined in include/btrfsutil.h:29
	BtrfsUtilVersionMinor = 1
	// BtrfsUtilVersionPatch as defined in include/btrfsutil.h:30
	BtrfsUtilVersionPatch = 1
	// BtrfsUtilCreateSnapshotRecursive as defined in include/btrfsutil.h:408
	BtrfsUtilCreateSnapshotRecursive = 1
	// BtrfsUtilCreateSnapshotReadOnly as defined in include/btrfsutil.h:412
	BtrfsUtilCreateSnapshotReadOnly = 2
	// BtrfsUtilCreateSnapshotMask as defined in include/btrfsutil.h:413
	BtrfsUtilCreateSnapshotMask = 3
	// BtrfsUtilDeleteSubvolumeRecursive as defined in include/btrfsutil.h:466
	BtrfsUtilDeleteSubvolumeRecursive = 1
	// BtrfsUtilDeleteSubvolumeMask as defined in include/btrfsutil.h:467
	BtrfsUtilDeleteSubvolumeMask = 1
	// BtrfsUtilSubvolumeIteratorPostOrder as defined in include/btrfsutil.h:498
	BtrfsUtilSubvolumeIteratorPostOrder = 1
	// BtrfsUtilSubvolumeIteratorMask as defined in include/btrfsutil.h:499
	BtrfsUtilSubvolumeIteratorMask = 1
)

// BtrfsError as declared in include/btrfsutil.h:42
type BtrfsError int32

// BtrfsError enumeration from include/btrfsutil.h:42
const (
	BtrfsUtilOk                          = iota
	BtrfsUtilErrorStopIteration          = 1
	BtrfsUtilErrorNoMemory               = 2
	BtrfsUtilErrorInvalidArgument        = 3
	BtrfsUtilErrorNotBtrfs               = 4
	BtrfsUtilErrorNotSubvolume           = 5
	BtrfsUtilErrorSubvolumeNotFound      = 6
	BtrfsUtilErrorOpenFailed             = 7
	BtrfsUtilErrorRmdirFailed            = 8
	BtrfsUtilErrorUnlinkFailed           = 9
	BtrfsUtilErrorStatFailed             = 10
	BtrfsUtilErrorStatfsFailed           = 11
	BtrfsUtilErrorSearchFailed           = 12
	BtrfsUtilErrorInoLookupFailed        = 13
	BtrfsUtilErrorSubvolGetflagsFailed   = 14
	BtrfsUtilErrorSubvolSetflagsFailed   = 15
	BtrfsUtilErrorSubvolCreateFailed     = 16
	BtrfsUtilErrorSnapCreateFailed       = 17
	BtrfsUtilErrorSnapDestroyFailed      = 18
	BtrfsUtilErrorDefaultSubvolFailed    = 19
	BtrfsUtilErrorSyncFailed             = 20
	BtrfsUtilErrorStartSyncFailed        = 21
	BtrfsUtilErrorWaitSyncFailed         = 22
	BtrfsUtilErrorGetSubvolInfoFailed    = 23
	BtrfsUtilErrorGetSubvolRootrefFailed = 24
	BtrfsUtilErrorInoLookupUserFailed    = 25
	BtrfsUtilErrorFsInfoFailed           = 26
)

// _ItimerWhich as declared in sys/time.h:89
type _ItimerWhich int32

// _ItimerWhich enumeration from sys/time.h:89
const ()
