// GPL-2

// WARNING: This file has automatically been generated on Sun, 01 Nov 2020 21:46:43 EST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package btrfsutil

/*
#cgo LDFLAGS: -lbtrfsutil
#include <btrfsutil.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// BtrfsQgroupInherit as declared in include/btrfsutil.h:363
type BtrfsQgroupInherit C.struct_btrfs_util_qgroup_inherit

// BtrfsSubvolumeInfo as declared in include/btrfsutil.h:180
type BtrfsSubvolumeInfo struct {
	Id             uint
	ParentId       uint
	DirId          uint
	Flags          uint
	Uuid           [16]byte
	ParentUuid     [16]byte
	ReceivedUuid   [16]byte
	Generation     uint
	Ctransid       uint
	Otransid       uint
	Stransid       uint
	Rtransid       uint
	ref92562e03    *C.struct_btrfs_util_subvolume_info
	allocs92562e03 interface{}
}

// BtrfsSubvolumeIterator as declared in include/btrfsutil.h:509
type BtrfsSubvolumeIterator C.struct_btrfs_util_subvolume_iterator
